package com.reservation_system.services;

import com.reservation_system.model.User;
import com.reservation_system.patterns.factory.UserFactory;
import com.reservation_system.repository.UserRepository;

public class RegistrationService {
    private final UserRepository userRepository;

    public RegistrationService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    public User registerUser(String type, String name, String email, String password) {
        validateAllowedRegistrationType(type);
        validateRegistrationInput(type, name, email, password);

        if (userRepository.emailExists(email)) {
            throw new IllegalArgumentException("Email is already registered.");
        }

        boolean approved = getDefaultApprovalStatus(type);
        int id = userRepository.getNextID();

        User newUser = UserFactory.createUser(type, id, name, email, password, approved);
        userRepository.addUser(newUser);

        return newUser;
    }

    private void validateRegistrationInput(String type, String name, String email, String password) {
        if (type == null || type.isBlank()) {
            throw new IllegalArgumentException("User type is required.");
        }

        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Name is required.");
        }

        if (email == null || email.isBlank()) {
            throw new IllegalArgumentException("Email is required.");
        }

        if (!isValidEmail(email)) {
            throw new IllegalArgumentException("Invalid email format.");
        }

        if (password == null || password.isBlank()) {
            throw new IllegalArgumentException("Password is required.");
        }

        if (!isStrongPassword(password)) {
            throw new IllegalArgumentException(
                    "Password must contain uppercase, lowercase, number, and symbol, and be at least 8 characters long."
            );
        }
    }

    private boolean isValidEmail(String email) {
        return email.contains("@") && email.contains(".");
    }

    private boolean isStrongPassword(String password) {
        if (password.length() < 8) {
            return false;
        }

        boolean hasUpper = false;
        boolean hasLower = false;
        boolean hasDigit = false;
        boolean hasSymbol = false;

        for (char c : password.toCharArray()) {
            if (Character.isUpperCase(c)) {
                hasUpper = true;
            } else if (Character.isLowerCase(c)) {
                hasLower = true;
            } else if (Character.isDigit(c)) {
                hasDigit = true;
            } else {
                hasSymbol = true;
            }
        }

        return hasUpper && hasLower && hasDigit && hasSymbol;
    }

    private boolean getDefaultApprovalStatus(String type) {
    switch (type.trim().toLowerCase()) {
        case "guest":
            return true;
        case "student":
        case "faculty":
        case "researcher":
        case "labmanager":
            return true;  // temporary simplification
        case "headlabcoordinator":
            return true;  
        default:
            throw new IllegalArgumentException("Invalid user type: " + type);
        }
    }

    private void validateAllowedRegistrationType(String type) {
    String normalized = type.trim().toLowerCase();

    switch (normalized) {
        case "student":
        case "faculty":
        case "researcher":
        case "guest":
            return;

        case "headlabcoordinator":
            if (userRepository.headLabCoordinatorExists()) {
                throw new IllegalArgumentException("A head lab coordinator account already exists.");
            }
            return;

        case "labmanager":
            throw new IllegalArgumentException("Lab manager accounts must be generated by the head lab coordinator.");

        default:
            throw new IllegalArgumentException("Invalid user type.");
        }
    }
}