package com.reservation_system.AI_assistant;

import com.reservation_system.Equipment.Equipment;
import com.reservation_system.Equipment.EquipmentType;
import com.reservation_system.Equipment.LabLocation;
import com.reservation_system.patterns.observer.EquipmentObserver;
import com.reservation_system.patterns.observer.EquipmentRegistry;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class EquipmentRegistryTest {

    private EquipmentRegistry registry;

    // simple observer that just records the last snapshot it received
    private static class TestObserver implements EquipmentObserver {
        List<Equipment> lastSnapshot;
        int callCount = 0;

        @Override
        public void onEquipmentListChanged(List<Equipment> updatedList) {
            lastSnapshot = updatedList;
            callCount++;
        }
    }

    private Equipment makeEquipment() {
        return new Equipment(UUID.randomUUID(), EquipmentType.MICROCONTROLLER, "Test Equipment", LabLocation.BERGERON300);
    }

    @BeforeEach
    void setUp() {
        registry = new EquipmentRegistry();
    }

    @Test
    void startsEmpty() {
        assertTrue(registry.getAll().isEmpty());
    }

    @Test
    void addEquipmentStoresIt() {
        Equipment eq = makeEquipment();
        registry.addEquipment(eq);
        assertEquals(1, registry.getAll().size());
        assertEquals(eq, registry.getAll().get(0));
    }

    @Test
    void observerNotifiedWhenEquipmentAdded() {
        TestObserver observer = new TestObserver();
        registry.addObserver(observer);

        registry.addEquipment(makeEquipment());

        assertEquals(1, observer.callCount);
        assertEquals(1, observer.lastSnapshot.size());
    }

    @Test
    void multipleObserversAllGetNotified() {
        TestObserver obs1 = new TestObserver();
        TestObserver obs2 = new TestObserver();
        registry.addObserver(obs1);
        registry.addObserver(obs2);

        registry.addEquipment(makeEquipment());

        assertEquals(1, obs1.callCount);
        assertEquals(1, obs2.callCount);
    }

    @Test
    void replaceAllSwapsOutEverything() {
        registry.addEquipment(makeEquipment());
        registry.addEquipment(makeEquipment());

        List<Equipment> newList = new ArrayList<>();
        newList.add(makeEquipment());
        registry.replaceAll(newList);

        assertEquals(1, registry.getAll().size());
    }

    @Test
    void observerNotifiedOnReplaceAll() {
        TestObserver observer = new TestObserver();
        registry.addObserver(observer);

        registry.replaceAll(new ArrayList<>());

        assertEquals(1, observer.callCount);
    }

    @Test
    void getAllReturnsUnmodifiableList() {
        registry.addEquipment(makeEquipment());
        List<Equipment> result = registry.getAll();
        assertThrows(UnsupportedOperationException.class, () -> result.add(makeEquipment()));
    }

    @Test
    void observerSnapshotMatchesRegistryContents() {
        TestObserver observer = new TestObserver();
        registry.addObserver(observer);

        Equipment eq1 = makeEquipment();
        Equipment eq2 = makeEquipment();
        registry.addEquipment(eq1);
        registry.addEquipment(eq2);

        assertEquals(2, observer.lastSnapshot.size());
        assertTrue(observer.lastSnapshot.contains(eq2));
    }

    // =========================================================================
    // AI-GENERATED TEST CASES
    // The following tests were automatically generated by an AI assistant.
    // =========================================================================

    @Test
    void addingMultipleEquipmentIncrementsSizeEachTime() {
        registry.addEquipment(makeEquipment());
        assertEquals(1, registry.getAll().size());
        registry.addEquipment(makeEquipment());
        assertEquals(2, registry.getAll().size());
        registry.addEquipment(makeEquipment());
        assertEquals(3, registry.getAll().size());
    }

    @Test
    void observerCallCountMatchesNumberOfAdditions() {
        TestObserver observer = new TestObserver();
        registry.addObserver(observer);

        registry.addEquipment(makeEquipment());
        registry.addEquipment(makeEquipment());
        registry.addEquipment(makeEquipment());

        assertEquals(3, observer.callCount);
    }

    @Test
    void replaceAllWithEmptyListClearsRegistry() {
        registry.addEquipment(makeEquipment());
        registry.addEquipment(makeEquipment());
        registry.replaceAll(new ArrayList<>());
        assertTrue(registry.getAll().isEmpty());
    }

    @Test
    void replaceAllNotifiesObserverWithCorrectSize() {
        TestObserver observer = new TestObserver();
        registry.addObserver(observer);

        List<Equipment> newList = new ArrayList<>();
        newList.add(makeEquipment());
        newList.add(makeEquipment());
        registry.replaceAll(newList);

        assertEquals(2, observer.lastSnapshot.size());
    }

    @Test
    void noObserversDoesNotThrowOnAdd() {
        assertDoesNotThrow(() -> registry.addEquipment(makeEquipment()));
    }

    @Test
    void noObserversDoesNotThrowOnReplaceAll() {
        assertDoesNotThrow(() -> registry.replaceAll(new ArrayList<>()));
    }

    @Test
    void snapshotPassedToObserverIsIndependentOfFurtherChanges() {
        TestObserver observer = new TestObserver();
        registry.addObserver(observer);

        registry.addEquipment(makeEquipment());
        List<Equipment> snapshotAfterFirst = new ArrayList<>(observer.lastSnapshot);

        registry.addEquipment(makeEquipment());

        // the snapshot captured after the first add should still have size 1
        assertEquals(1, snapshotAfterFirst.size());
    }
}