package com.reservation_system.AI_assistant;

import com.reservation_system.model.*;
import com.reservation_system.repository.UserRepository;
import com.reservation_system.services.RegistrationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

public class UserRegistrationServiceAITest {

    private RegistrationService registrationService;
    private final Path testFile = Path.of("data/test-users.csv");

    @BeforeEach
    void setUp() throws Exception {
        Files.createDirectories(testFile.getParent());

        Files.writeString(testFile,
                "name,id,email,password,type,approved\n" +
                "t1,1,t1@yorku.ca,T1@test!,student,true\n" +
                "t2,2,t2@yorku.ca,T2@test!,faculty,true\n" +
                "t3,3,t3@yorku.ca,T3@test!,guest,true\n"
        );

        UserRepository repository = new UserRepository("data/test-users.csv");
        registrationService = new RegistrationService(repository);
    }

    @Test
    void shouldRegisterValidGuest() {
        User user = registrationService.registerUser(
                "guest", "guest1", "guest1@gmail.com", "Strong1!"
        );

        assertAll(
                () -> assertNotNull(user),
                () -> assertInstanceOf(Guest.class, user),
                () -> assertEquals("guest", user.getUserType().toLowerCase()),
                () -> assertTrue(user.isApproved())
        );
    }

    @Test
    void shouldRegisterValidStudent() {
        User user = registrationService.registerUser(
                "student", "student1", "student1@yorku.ca", "Strong1!"
        );

        assertAll(
                () -> assertNotNull(user),
                () -> assertInstanceOf(Student.class, user),
                () -> assertEquals("student", user.getUserType().toLowerCase()),
                () -> assertTrue(user.isApproved())
        );
    }

    @Test
    void shouldRegisterValidFaculty() {
        User user = registrationService.registerUser(
                "faculty", "faculty1", "faculty1@yorku.ca", "Strong1!"
        );

        assertAll(
                () -> assertNotNull(user),
                () -> assertInstanceOf(Faculty.class, user),
                () -> assertEquals("faculty", user.getUserType().toLowerCase()),
                () -> assertTrue(user.isApproved())
        );
    }

    @Test
    void shouldRegisterValidResearcher() {
        User user = registrationService.registerUser(
                "researcher", "researcher1", "researcher1@yorku.ca", "Strong1!"
        );

        assertAll(
                () -> assertNotNull(user),
                () -> assertInstanceOf(Researcher.class, user),
                () -> assertEquals("researcher", user.getUserType().toLowerCase()),
                () -> assertTrue(user.isApproved())
        );
    }

    @Test
    void shouldAllowFirstHeadLabCoordinatorRegistration() {
        User user = registrationService.registerUser(
                "headlabcoordinator", "Coordinator", "coord@yorku.ca", "Strong1!"
        );

        assertAll(
                () -> assertNotNull(user),
                () -> assertInstanceOf(HeadLabCoordinator.class, user),
                () -> assertEquals("headlabcoordinator", user.getUserType().toLowerCase()),
                () -> assertTrue(user.isApproved())
        );
    }

    @Test
    void shouldRejectSecondHeadLabCoordinatorRegistration() {
        registrationService.registerUser(
                "headlabcoordinator", "Coordinator1", "coord1@yorku.ca", "Strong1!"
        );

        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "headlabcoordinator", "Coordinator2", "coord2@yorku.ca", "Strong1!"
                )
        );

        assertEquals("A head lab coordinator account already exists.", ex.getMessage());
    }

    @Test
    void shouldRejectLabManagerSelfRegistration() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "labmanager", "Manager1", "manager1@yorku.ca", "Strong1!"
                )
        );

        assertEquals("Lab manager accounts must be generated by the head lab coordinator.", ex.getMessage());
    }

    @Test
    void shouldRejectDuplicateEmail() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "t1@yorku.ca", "Strong1!"
                )
        );

        assertEquals("Email is already registered.", ex.getMessage());
    }

    @Test
    void shouldRejectInvalidEmail() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "invalid-email", "Strong1!"
                )
        );

        assertEquals("Invalid email format.", ex.getMessage());
    }

    @Test
    void shouldRejectBlankEmail() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "", "Strong1!"
                )
        );

        assertEquals("Email is required.", ex.getMessage());
    }

    @Test
    void shouldRejectNullEmail() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", null, "Strong1!"
                )
        );

        assertEquals("Email is required.", ex.getMessage());
    }

    @Test
    void shouldRejectBlankName() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "", "new@yorku.ca", "Strong1!"
                )
        );

        assertEquals("Name is required.", ex.getMessage());
    }

    @Test
    void shouldRejectNullName() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", null, "new@yorku.ca", "Strong1!"
                )
        );

        assertEquals("Name is required.", ex.getMessage());
    }

    @Test
    void shouldRejectInvalidType() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "admin", "test", "new@yorku.ca", "Strong1!"
                )
        );

        assertEquals("Invalid user type.", ex.getMessage());
    }

    @Test
    void shouldRejectBlankType() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "", "test", "new@yorku.ca", "Strong1!"
                )
        );

        assertEquals("Invalid user type.", ex.getMessage());
    }

    @Test
    void shouldRejectWhitespaceType() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "   ", "test", "new@yorku.ca", "Strong1!"
                )
        );

        assertEquals("Invalid user type.", ex.getMessage());
    }

    @Test
    void shouldThrowNullPointerExceptionForNullTypeInCurrentImplementation() {
        assertThrows(NullPointerException.class, () ->
                registrationService.registerUser(
                        null, "test", "new@yorku.ca", "Strong1!"
                )
        );
    }

    @Test
    void shouldAllowTrimmedAndCaseInsensitiveGuestType() {
        User user = registrationService.registerUser(
                "   GuEsT   ", "guest2", "guest2@gmail.com", "Strong1!"
        );

        assertAll(
                () -> assertNotNull(user),
                () -> assertInstanceOf(Guest.class, user),
                () -> assertEquals("guest", user.getUserType().toLowerCase())
        );
    }

    @Test
    void shouldRejectBlankPassword() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "new@yorku.ca", ""
                )
        );

        assertEquals("Password is required.", ex.getMessage());
    }

    @Test
    void shouldRejectNullPassword() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "new@yorku.ca", null
                )
        );

        assertEquals("Password is required.", ex.getMessage());
    }

    @Test
    void shouldRejectPasswordWithoutUppercase() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "new1@yorku.ca", "weak1!aa"
                )
        );

        assertEquals(
                "Password must contain uppercase, lowercase, number, and symbol, and be at least 8 characters long.",
                ex.getMessage()
        );
    }

    @Test
    void shouldRejectPasswordWithoutLowercase() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "new2@yorku.ca", "WEAK1!AA"
                )
        );

        assertEquals(
                "Password must contain uppercase, lowercase, number, and symbol, and be at least 8 characters long.",
                ex.getMessage()
        );
    }

    @Test
    void shouldRejectPasswordWithoutNumber() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "new3@yorku.ca", "Weak!!!!"
                )
        );

        assertEquals(
                "Password must contain uppercase, lowercase, number, and symbol, and be at least 8 characters long.",
                ex.getMessage()
        );
    }

    @Test
    void shouldRejectPasswordWithoutSymbol() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "new4@yorku.ca", "Weak1234"
                )
        );

        assertEquals(
                "Password must contain uppercase, lowercase, number, and symbol, and be at least 8 characters long.",
                ex.getMessage()
        );
    }

    @Test
    void shouldRejectShortPassword() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class, () ->
                registrationService.registerUser(
                        "student", "test", "new5@yorku.ca", "S1!a"
                )
        );

        assertEquals(
                "Password must contain uppercase, lowercase, number, and symbol, and be at least 8 characters long.",
                ex.getMessage()
        );
    }

    @Test
    void shouldPersistRegisteredUserToCsv() {
        registrationService.registerUser(
                "guest", "persist", "persist@gmail.com", "Strong1!"
        );

        UserRepository newRepository = new UserRepository("data/test-users.csv");
        assertTrue(newRepository.emailExists("persist@gmail.com"));
    }

    @Test
    void shouldAssignNextAvailableIdToRegisteredUser() {
        User newUser = registrationService.registerUser(
                "guest", "nextid", "nextid@gmail.com", "Strong1!"
        );

        assertEquals(4, newUser.getID());
    }
}
